name: Coverage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "coverage"
  coverage:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - uses: actions/checkout@main
        - name: Setup Go environment
          uses: actions/setup-go@v3.0.0
        - name: Generate coverage report
            run: ./codecov.sh
        - name: Codecov
          uses: codecov/codecov-action@v3.1.0
          with:
            files: ./coverage.txt
